In [1]:
import numpy as np


In [3]:
a = np.array(7)
print(a)
print(a.ndim)

7
0


In [4]:
b = np.array([5,3,6,7,8])
print(b)
print(b.ndim)
print(type(b))

[5 3 6 7 8]
1
<class 'numpy.ndarray'>


In [8]:
list =[]
print(type(list))
c = np.array(list)
print(type(c))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
# shap ----->
for i in range(1,5):
        x = int(input('element: '))
        list.append(x)
d = np.array(list)
print(d)

element: 7
element: 6
element: 9
element: 8
[7 6 9 8]


In [11]:
type(d)

numpy.ndarray

In [12]:
list
type(list)

list

In [14]:
 e = np.zeros(4)
print(e)

[0. 0. 0. 0.]


In [17]:
f = np.ones(5)
print(f)


[1. 1. 1. 1. 1.]


In [21]:
h = np.arange(6)
print(h)

[0 1 2 3 4 5]


In [22]:
#np.arange(start,stop,steps,datatype)
g = np.arange(4,10)
print(g)

[4 5 6 7 8 9]


In [24]:
i =np.arange(0,10,3)
i

array([0, 3, 6, 9])

In [30]:
#Spacial methods
#1)Linespace
k= np.linspace(0,10, num= 5)
k

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
#Random methods 
k= np.random.rand(4)
k  

array([0.08239028, 0.79302789, 0.52123365, 0.16487631])

In [40]:
#(-1 -> +1)
l= np.random.randn(5)
l  

array([ 0.42703205,  0.53771237, -0.14819113,  0.07117984,  0.55283651])

In [55]:
p= np.random.ranf(5)
print(p)
p.dtype

[0.39658218 0.61070348 0.93167318 0.33042514 0.35601909]


dtype('float64')

In [52]:
# (start,stop,count)
s= np.random.randint(4,20,6)
print(s)  
s.dtype

[17 18  6 14  5  8]


dtype('int32')

In [53]:
#linespace
#(min ,max, count)
o = np.linspace(100,1000, num= 5)
o

array([ 100.,  325.,  550.,  775., 1000.])

In [54]:
o.dtype


dtype('float64')

In [61]:
 p = np.array(['Gulshan','Rohan', 'Rahulverma'])
p.dtype

dtype('<U10')

In [62]:
t= np.array(['A','Bo'])
t.dtype

dtype('<U2')

In [59]:
m= np.array(['A'])
m.dtype

dtype('<U1')

In [65]:
# n = np.array([45e789])
# n.dtype

n = np.array([45789])
n.dtype

dtype('int32')

In [66]:
t = np.array([2+3j])
t.dtype

dtype('complex128')

In [67]:
v = np.array(['a','s','w', 4,7,8])
v.dtype

dtype('<U11')

In [73]:
w = np.array([2,5,4,7, ],   dtype = np.float_)#dtype= np.int_ 
print(w)
print(w.dtype)

[2. 5. 4. 7.]
float64


In [74]:
y = np.array([2,5,4,7,8.4,4.1, ],   dtype = np.int_)#dtype= np.int_ 
print(y)
print(y.dtype)

[2 5 4 7 8 4]
int32


In [75]:
z = np.float32(y)
print (z)

[2. 5. 4. 7. 8. 4.]


In [85]:
%timeit [x**3 for x in range(1, 20)]

1.4 µs ± 31.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [87]:
%timeit np.arange(1, 20)**3

1.89 µs ± 37.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [88]:
a = np.array([
    [7,5,2],[5,4,1],[8,9,4]
])
a.ndim

2

In [90]:
c = [
    [5,8,9,'Gulshan']
]

In [91]:
c [0]

[5, 8, 9, 'Gulshan']

In [92]:
# 2 dimision list 
c[0][1]

8

In [96]:
#4 dim list
d [[[[7,8,9]]]]

In [97]:
d[0][0][0][0]

7

In [98]:
e = [[[[7,8,9,['a','b','c']]]]]

In [105]:
e[0][0][0][1]

8

In [111]:
h= np.zeros((6,4))
h

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
i = np.ones((4,3))
i

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [110]:
j= np.eye(4)
j

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [116]:
k =np.eye(4,5)
print(k)
print(k.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
2


In [117]:
l = np.random.rand(3,4)
l

array([[0.58724675, 0.1207352 , 0.57801231, 0.45163047],
       [0.79623779, 0.33961334, 0.41933059, 0.49571658],
       [0.41555965, 0.25959254, 0.28894411, 0.46709569]])

In [119]:
m = np.random.randint(2,10,2)
m

array([7, 4])

In [122]:
a = np.array([3,5,7,1,6,4,1,2])
print(a.ndim)
b = a.reshape(2,4)
print(b)
print(b.ndim)

1
[[3 5 7 1]
 [6 4 1 2]]
2


In [125]:
g = np.array([3,5,7,1,6,4,1,2,7,8,9,7])
print(g.ndim)
p = g.reshape(4,3)
print(p)
print(p.ndim)

1
[[3 5 7]
 [1 6 4]
 [1 2 7]
 [8 9 7]]
2


In [ ]:
g = np.array([3,5,7,1,6,4,1,2,7,8,9,7])


In [ ]:
g= [[[100,200,300],['ad','bd'],[[[[5,8,2,4],[45,78,5],['a','b','e']]]]]]
target  a

# 27 sep 

In [8]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print(a.shape)
b =np.array([5,2,7,8,9,0,1])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[5 2 7 8 9 0 1]
(7,)


In [11]:
c = np.array([[[5,5,7,8,9,4,5,4,8,5,4,1,2,3]]])
print(c)
print(c.shape)

[[[5 5 7 8 9 4 5 4 8 5 4 1 2 3]]]
(1, 1, 14)


In [16]:
d = np.array([
    [3,7,7,5],
    [7,9,7,4],
    [2,5,7,1]
])
d.shape

(3, 4)

In [22]:
e = np.array([
    [
        [2,4,1],
        [4,7,8],
        [7,5,9]
    ]
])
e.shape

(1, 3, 3)

In [23]:
e.ndim

3

In [26]:
#  Single  Dimensional Array
l= np.array([3,7,9,2,4])
#            0,1,2,3,4
#            -5,-4,-3,-2,-1
l [1]
l[-2]

2

In [36]:
# Two Dimensional Array
p= np.array([
    [3,7,9,2,4],
    [7,4,8,7,9]
])
p[0][1]
#p[1,4]
p[1][4]
p[-0][-2]

2

In [38]:
h= np.array([
    [[8,3,5],
     [7,2,3]
    ]])
h.shape

(1, 2, 3)

In [47]:
h[0,0,0]

8

In [48]:
a =np.array([4,2,6,3])
b = np.array([8,3,4,6])
a+b

array([12,  5, 10,  9])

In [51]:
v =np.array([4,2,6])
b =np.array([8,3,4])


In [52]:
v-b

array([-4, -1,  2])

In [53]:
v*b

array([32,  6, 24])

In [54]:
v/b

array([0.5       , 0.66666667, 1.5       ])

In [56]:
v+b

array([16,  6,  8])

In [57]:
v%b

array([0, 0, 0])

In [58]:
d = np.array([1,2,3,4])
# 1/1=1 , 1/2=0.5, 1/3=0 ,
np.reciprocal(d)

array([1, 0, 0, 0])

In [61]:
d

array([1, 2, 3, 4])

In [62]:
np.max(d)

4

In [63]:
np.sqrt(d)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [64]:
np.sin(d)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [65]:
np.cos(d)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [67]:
print (d)
print(np.max(d))
print(np.argmax(d))

[1 2 3 4]
4
3


In [68]:
print(np.min(d))
print(np.argmin(d))

1
0


In [69]:
b= np.array([9,1,4,7,5,5,5,6,3,9])
np.argmin(b)   

1

In [73]:
b = np.array([1, 2, 3, 4, 5])
print("Original Array:")
print(b)
sum = np.cumsum(b)
print("Processed Array:")
print(sum)

Original Array:
[1 2 3 4 5]
Processed Array:
[ 1  3  6 10 15]


In [75]:
b = np.array([54,24,23,25,26])
b.nbytes

20

In [81]:
b = np.array([54, 24, 23, 25, 26])
size = b.nbytes
print("Memory size in bytes:", size)

Memory size in bytes: 20


In [99]:
c = np.array([54, 24, 23, 25, 26,21])
d = c.reshape(2, 3)
print(d)

[[54 24 23]
 [25 26 21]]


In [118]:
#Broadcasting ...................................................
a = np.array([4, 5, 5, 1, 2, 3, 4])
b = np.array([7, 8, 9])
b = b.reshape(1, 3)  
b+ b

array([[14, 16, 18]])

In [116]:
# Broadcast error ->dimension same+ similar shape/shape
