In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy
numpy.version.version


'1.24.4'

In [6]:
import numpy as np


In [8]:
arr0 = np.array(5)

In [9]:
print(arr0)

5


In [10]:
type(arr0)

numpy.ndarray

In [11]:
arr0.ndim

0

In [13]:
arr1 = np.array([5,2,3.4])

In [14]:
type(arr1)

numpy.ndarray

In [15]:
arr1.ndim

1

In [16]:
print (arr1)

[5.  2.  3.4]


In [19]:
a1 = np.array([3,6,4,1])
print(a1)
print(type(a1))
print(a1.ndim)

[3 6 4 1]
<class 'numpy.ndarray'>
1


In [23]:
b = [1,2,3, True ,(2,5), "Gulshan ",{3,4}]
print(b)
type(b)

[1, 2, 3, True, (2, 5), 'Gulshan ', {3, 4}]


list

In [28]:
c = np.array ([ 1,2,3,3,4])
print(c)

[1 2 3 3 4]


In [29]:
d = np.array([ 'c','d','e',4])
print(d)

['c' 'd' 'e' '4']


In [30]:
e = np.array([5+9j,4,7,8])
print(e)

[5.+9.j 4.+0.j 7.+0.j 8.+0.j]


In [38]:
arr2 = np.array ([
    [4,7,8,9],
    [0,7,8,3]


]) 
arr2.ndim

2

In [40]:
arr3 = np.array([
    [5,9]
])
arr3.ndim

2

In [42]:
arr4 = np.array([
    [
        [
            [6,4,78],[7,5,4]
        ]
    ]
])
arr4.ndim

4