In [3]:
a = [2,3,4,5,7,]
type(a)

list

In [4]:
b = [1,2,4,5,True,(1,2),"Mahi",{2,3}]
type(b)

list

In [19]:
import numpy

In [20]:
#np -> standard
#natplotlib.pyplot  as plt mt
import numpy as np
np.__version__

'1.25.2'

In [21]:
arr0 = np.array(5)

In [22]:
print(arr0)

5


In [23]:
type(arr0)

numpy.ndarray

In [24]:
#ndim -> no of dimension
arr0.ndim

0

In [25]:
arr1 = np.array([5,5,2,3,4.5])
print(arr1)

[5.  5.  2.  3.  4.5]


In [26]:
type(arr1)

numpy.ndarray

In [27]:
arr1.ndim

1

In [28]:
a1 = np.array([3,6,4,1,""])
print(a1)
type(a1)
print(type(a1))
print(a1.ndim)

['3' '6' '4' '1' '']
<class 'numpy.ndarray'>
1


In [29]:
a3 = np.array([7,9,5,8,4,3,5])
print(a3)

[7 9 5 8 4 3 5]


In [30]:
arr2 = np.array([
    [5,6,4],
    [2,4,7]
])
arr2.ndim

2

In [31]:
arr3 = np.array(
[
    [9,8]
])
arr3.ndim

2

In [32]:
arr4 = np.array(
    [
        [
            [6,4,5],[4,5,2],[5,5,2],
        ]
    ]
)
arr4.ndim

3

# 26-09-2023

In [33]:
import numpy as np


a = np.array(7)
print(a)
print(type(a))
print(a.ndim)

7
<class 'numpy.ndarray'>
0


In [34]:
b = np.array([5,4,6,8])
print(b)
print(type(b))
print(b.ndim)

[5 4 6 8]
<class 'numpy.ndarray'>
1


In [35]:
my_list = []
c = np.array(my_list)
print(type(my_list))
print(type(c))

<class 'list'>
<class 'numpy.ndarray'>


In [36]:
for i in range(1,5):
    x = int(input('elements:'))
    my_list.append(x)
d = np.array(my_list)
print(d)

elements:


ValueError: invalid literal for int() with base 10: ''

In [37]:
type(d)


NameError: name 'd' is not defined

In [38]:
my_list
type(my_list)

list

In [39]:
e = np.zeros(4)
print(e)

[0. 0. 0. 0.]


In [40]:
f = np.ones(5)
print(f)

[1. 1. 1. 1. 1.]


In [41]:
g = np.arange(10)
print(g)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
#np.arange(start,stop,steps,dtype)
h = np.arrange(5,10)
h

AttributeError: module 'numpy' has no attribute 'arrange'

In [43]:
#steps
i = np.arange(0,10,2)
i

array([0, 2, 4, 6, 8])

In [44]:
j = np.arange(0,30,3)
j

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [45]:
#spacial
#linespace
j = np.linspace(0,10, num= 5)
j

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [46]:
#variance -> IQR (25%),(50%),(75%),(100%)

In [47]:
k = np.random.rand(4) #(0-4)
k


array([0.06469988, 0.73970198, 0.35285305, 0.69047988])

In [48]:
#(-1 -> +1)
l = np.random.randn(7)
l

array([-1.91760367,  0.1975309 ,  0.0437429 ,  1.31176099,  1.38795371,
        0.6688998 , -0.98636753])

In [49]:
m = np.random.ranf(6)
m

array([0.37426328, 0.78185483, 0.76093337, 0.25463358, 0.3948739 ,
       0.58082087])

In [50]:
#(start,stop,count)# 6 start , 20 stop , 7 count
n = np.random.randint(6,20,7)
n

array([18, 14, 10, 17, 17,  7,  8])

In [51]:
o = np.linspace(100,1000,num=5)
o


array([ 100.,  325.,  550.,  775., 1000.])

In [52]:
print(o.dtype)

float64


In [53]:
print(d.dtype)

NameError: name 'd' is not defined

In [54]:
p = np.array(['Manisha','Seema','Mahi','Saini'])
p.dtype

dtype('<U7')

In [55]:
q = np.array(['K'])
q.dtype

dtype('<U1')

In [56]:
r = np.array([True])
r.dtype

dtype('bool')

In [57]:
s = np.array([1])
s.dtype

dtype('int32')

In [58]:
t = np.array([0+1j])
t.dtype

dtype('complex128')

In [59]:
u = np.array(['a','s','w','x',5,4,2,3,True])#is case me U11 hi mile ga.
u.dtype

dtype('<U11')

In [60]:
v = np.array([2,5,7,8], dtype = np.int_)
print(v)
print(v.dtype)

[2 5 7 8]
int32


In [61]:
w = np.array([4,5,6,7], dtype = np.float_)
print(w)
print(w.dtype)

[4. 5. 6. 7.]
float64


In [62]:
x = np.array([5,6,3,4])
print(x)
print(x.dtype)

[5 6 3 4]
int32


In [63]:
z = np.longfloat(y)
print(z)
print(z.dtype)

NameError: name 'y' is not defined

In [64]:
#list & Arrays -> Datatype
a = []
type(a)

list

In [65]:
b = [i**2 for i in range(1,10)]
b

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [66]:
%timeit [ i**2 for i in  range(1,15)]

894 ns ± 6.88 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [67]:
import numpy as np
%timeit np.arange(1,15)**2

1.01 µs ± 9.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [68]:
%timeit [x**3 for x in range(1,20)]

1.28 µs ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [69]:
import numpy as np

In [70]:
%timeit np.arange(1,20)**3

1.73 µs ± 21.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [71]:
np.arange(1,15)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196])

In [72]:
a = np.array([
    [6,7],[4,5],[6,9]
])
a.ndim

2

In [73]:
b = np.array([[[]]])
b.ndim

3

In [74]:
c =[[5,6,7,8,'Mahi']]
c

[[5, 6, 7, 8, 'Mahi']]

In [75]:
d = [[[[5,6,8],['a','m','k']]]] 

In [76]:
d[0][0][1][0]

'a'

In [77]:
e = np.array([[[8,6,4]]])
e.ndim

3

In [78]:
f = np.array([[[[[[[[[[4,6,8]]]]]]]]]])
f.ndim

10

In [79]:
g = np.arange(3,3)
g
g.ndim

1

In [80]:
h = np.zeros((3,4))
h


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
i = np.ones((3,3))
i

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
j = np.eye(3)
j

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
k = np.eye(4,6)
k

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [84]:
k = np.eye(4,6)
print(k)
k.ndim

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


2

In [85]:
l = np.random.rand(3,4)
l

array([[0.39365936, 0.27037332, 0.67710331, 0.71029696],
       [0.34132565, 0.97545889, 0.3627934 , 0.23363551],
       [0.63933749, 0.69856397, 0.28729723, 0.81560755]])

m = np.random.randint((2,10),(4,5))
m

In [86]:
m = np.random.randint((2,4,6,8,3))
m

array([1, 2, 1, 1, 1])

## 27-09-2023

In [87]:
#shape #4 element 2 rows
import numpy
a = numpy.array([[2,3,5,6],[3,5,8,7]])
a.shape

(2, 4)

In [88]:
b = numpy.array([[[[4,5,2,7,8]]]])
b.shape

(1, 1, 1, 5)

In [89]:
c = numpy.array([[3,5,6],[5,7,9],[3,5,8],[3,5,8]])
c.shape

(4, 3)

In [90]:
c = numpy.array([[3,5,6],[5,7,9],[3,5,8]])
c.shape

(3, 3)

In [91]:
d = numpy.array([[3,4,6,7],[7,8,9,8]])
d.shape
d.ndim

2

In [92]:
e = numpy.array([
    [
        [3,4,5],
        [3,5,7],
        [2,8,9],
        [9,6,4],
    ]
])
e.shape

(1, 4, 3)

In [93]:
e.ndim

3

In [94]:
f = numpy.array([3,4,6,5,8])
f[1]
# 0 1 2 3 4
# -4 -3 -2 -1 

4

In [95]:
f[-2]

5

In [96]:
g = numpy.array([
    [7,5,4],
    [4,5,7]
])
g[1,2]


7

In [97]:
g[-1,-2]

5

In [98]:
h = numpy.array([[[5,6,3,7],[2,5,1,8]]])
#h.ndim
h[0]

array([[5, 6, 3, 7],
       [2, 5, 1, 8]])

In [99]:
h[0]

array([[5, 6, 3, 7],
       [2, 5, 1, 8]])

In [100]:
#matrix addition
a = numpy.array([4,3,5,6])
b = numpy.array([3,2,5,6])
a+b

array([ 7,  5, 10, 12])

In [101]:
#matrix subtraction
a = numpy.array([4,3,5,6])
b = numpy.array([3,2,5,6])
a-b

array([1, 1, 0, 0])

In [102]:
#matrix multiplication
a = numpy.array([4,3,5,6])
b = numpy.array([3,2,5,6])
a*b

array([12,  6, 25, 36])

In [103]:
#matrix divison
a = numpy.array([4,3,5,6])
b = numpy.array([3,2,5,6])
a/b

array([1.33333333, 1.5       , 1.        , 1.        ])

In [104]:
#matrix addition
a = numpy.array([[4,3,5,6],[2,3,4,6]])
b = numpy.array([[3,2,5,6],[2,1,3,4]])
a+b

array([[ 7,  5, 10, 12],
       [ 4,  4,  7, 10]])

In [105]:
a-b

array([[1, 1, 0, 0],
       [0, 2, 1, 2]])

In [106]:
a*b

array([[12,  6, 25, 36],
       [ 4,  3, 12, 24]])

In [107]:
z = numpy.array([1,2,4,5])
numpy.reciprocal(z)

array([1, 0, 0, 0])

In [108]:
1/z

array([1.  , 0.5 , 0.25, 0.2 ])

In [109]:
numpy.max(z)

5

In [110]:
numpy.min(z)

1

In [111]:
numpy.sqrt(z)

array([1.        , 1.41421356, 2.        , 2.23606798])

In [112]:
numpy.sin(z)

array([ 0.84147098,  0.90929743, -0.7568025 , -0.95892427])

In [119]:
print(numpy.max(z)) # 5 maximum  3 index position
print(numpy.argmax(z))

5
3


In [120]:
print(numpy.min(z))
print(numpy.argmin(z))

1
0


In [121]:
print(z) #cumsum is the sum of numbers.
print()
print(numpy.cumsum(z))

[1 2 4 5]

[ 1  3  7 12]


In [116]:
import numpy
b = numpy.array([23,13,45,67])
b.nbytes

16

In [117]:
c = numpy.array([[2,3],[4,5]])
c.nbytes

16

In [122]:
b = numpy.array([2,4,6,8])
b.ndim

1

In [123]:
d = b.reshape(2,2)
d

array([[2, 4],
       [6, 8]])

In [126]:
e = numpy.array([1,2,3,4,5,6,7,8,9,1,2,3])
f = e.reshape(4,2)
f

ValueError: cannot reshape array of size 12 into shape (4,2)

In [ ]:
g = numpy.array([3,4,5,7,8,9])

In [ ]:
h = g.reshape(2,3)
h

In [ ]:
h.ndim

In [ ]:
g.reshape(1,2,3)

In [ ]:
h = g.reshape(2,1,3)
h

In [ ]:
h.ndim

In [ ]:
h[1]

In [ ]:
h[1,0]

In [ ]:
#Broadcasting

In [ ]:
a = numpy.array([2,3,5,6,7])
b = numpy.array([5])
a+b

In [ ]:
a = numpy.array([[2,3],[4,5]])
a.shape