In [3]:
a = [2,3,4,5,7,]
type(a)

list

In [4]:
b = [1,2,4,5,True,(1,2),"Mahi",{2,3}]
type(b)

list

In [19]:
import numpy

In [20]:
#np -> standard
#natplotlib.pyplot  as plt mt
import numpy as np
np.__version__

'1.25.2'

In [21]:
arr0 = np.array(5)

In [22]:
print(arr0)

5


In [23]:
type(arr0)

numpy.ndarray

In [24]:
#ndim -> no of dimension
arr0.ndim

0

In [25]:
arr1 = np.array([5,5,2,3,4.5])
print(arr1)

[5.  5.  2.  3.  4.5]


In [26]:
type(arr1)

numpy.ndarray

In [27]:
arr1.ndim

1

In [28]:
a1 = np.array([3,6,4,1,""])
print(a1)
type(a1)
print(type(a1))
print(a1.ndim)

['3' '6' '4' '1' '']
<class 'numpy.ndarray'>
1


In [29]:
a3 = np.array([7,9,5,8,4,3,5])
print(a3)

[7 9 5 8 4 3 5]


In [30]:
arr2 = np.array([
    [5,6,4],
    [2,4,7]
])
arr2.ndim

2

In [31]:
arr3 = np.array(
[
    [9,8]
])
arr3.ndim

2

In [32]:
arr4 = np.array(
    [
        [
            [6,4,5],[4,5,2],[5,5,2],
        ]
    ]
)
arr4.ndim

3

# 26-09-2023

In [33]:
import numpy as np


a = np.array(7)
print(a)
print(type(a))
print(a.ndim)

7
<class 'numpy.ndarray'>
0


In [34]:
b = np.array([5,4,6,8])
print(b)
print(type(b))
print(b.ndim)

[5 4 6 8]
<class 'numpy.ndarray'>
1


In [35]:
my_list = []
c = np.array(my_list)
print(type(my_list))
print(type(c))

<class 'list'>
<class 'numpy.ndarray'>


In [127]:
for i in range(1,5):
    x = int(input('elements:'))
    my_list.append(x)
d = np.array(my_list)
print(d)

elements:4
elements:3
elements:2
elements:4
[4 3 2 4]


In [129]:
type(d)


numpy.ndarray

In [130]:
my_list
type(my_list)

list

In [131]:
e = np.zeros(4)
print(e)

[0. 0. 0. 0.]


In [132]:
f = np.ones(5)
print(f)

[1. 1. 1. 1. 1.]


In [133]:
g = np.arange(10)
print(g)

[0 1 2 3 4 5 6 7 8 9]


In [137]:
#np.arange(start,stop,steps,dtype)
h = np.arange(5,10)
h

array([5, 6, 7, 8, 9])

In [141]:
#steps
i = np.arange(0,10,2)
i

array([0, 2, 4, 6, 8])

In [142]:
j = np.arange(0,30,3)
j

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [143]:
#spacial
#linespace
j = np.linspace(0,10, num= 5)
j

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [144]:
#variance -> IQR (25%),(50%),(75%),(100%)

In [145]:
k = np.random.rand(4) #(0-4)
k


array([0.08304402, 0.81194891, 0.23018323, 0.46568652])

In [146]:
#(-1 -> +1)
l = np.random.randn(7)
l

array([-0.15291943,  0.43134681,  1.72608239,  0.28335151,  2.17977036,
        0.08037784, -1.60082591])

In [147]:
m = np.random.ranf(6)
m

array([0.10256455, 0.86120543, 0.44488385, 0.80083028, 0.58884656,
       0.56231859])

In [148]:
#(start,stop,count)# 6 start , 20 stop , 7 count
n = np.random.randint(6,20,7)
n

array([18, 11,  8, 12, 12,  8,  6])

In [149]:
o = np.linspace(100,1000,num=5)
o


array([ 100.,  325.,  550.,  775., 1000.])

In [150]:
print(o.dtype)

float64


In [151]:
print(d.dtype)
d

int32


array([4, 3, 2, 4])

In [152]:
p = np.array(['Manisha','Seema','Mahi','Saini'])
p.dtype

dtype('<U7')

In [153]:
q = np.array(['K'])
q.dtype

dtype('<U1')

In [154]:
r = np.array([True])
r.dtype

dtype('bool')

In [155]:
s = np.array([1])
s.dtype

dtype('int32')

In [156]:
t = np.array([0+1j])
t.dtype

dtype('complex128')

In [157]:
u = np.array(['a','s','w','x',5,4,2,3,True])#is case me U11 hi mile ga.
u.dtype

dtype('<U11')

In [158]:
v = np.array([2,5,7,8], dtype = np.int_)
print(v)
print(v.dtype)

[2 5 7 8]
int32


In [159]:
w = np.array([4,5,6,7], dtype = np.float_)
print(w)
print(w.dtype)

[4. 5. 6. 7.]
float64


In [160]:
x = np.array([5,6,3,4])
print(x)
print(x.dtype)

[5 6 3 4]
int32


In [161]:
z = np.longfloat(x)
print(z)
print(z.dtype)

[5. 6. 3. 4.]
float64


In [162]:
#list & Arrays -> Datatype
a = []
type(a)

list

In [163]:
b = [i**2 for i in range(1,10)]
b

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [164]:
%timeit [ i**2 for i in  range(1,15)]

897 ns ± 6.66 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [168]:
import numpy as np
%timeit np.arange(1,15)**2

1.02 µs ± 16.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [169]:
%timeit [x**3 for x in range(1,20)]

1.26 µs ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [170]:
import numpy as np

In [171]:
%timeit np.arange(1,20)**3

1.68 µs ± 12 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [172]:
np.arange(1,15)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196])

In [184]:
a = np.array([
    [6,7],[4,5],[6,9]
])
a.ndim

2

In [185]:
b = np.array([[[]]])
b.ndim

3

In [186]:
c =[[5,6,7,8,'Seema']]
c

[[5, 6, 7, 8, 'Seema']]

In [187]:
d = [[[[5,6,8],['a','m','k']]]] 
d

[[[[5, 6, 8], ['a', 'm', 'k']]]]

In [188]:
d[0][0][1][0]
d

[[[[5, 6, 8], ['a', 'm', 'k']]]]

In [189]:
e = np.array([[[8,6,4]]])
e.ndim

3

In [190]:
f = np.array([[[[[[[[[[4,6,8]]]]]]]]]])
f.ndim

10

In [191]:
g = np.arange(3,3)
g
g.ndim

1

In [192]:
h = np.zeros((3,4))
h


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [193]:
i = np.ones((3,3))
i

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [194]:
j = np.eye(3)
j

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [195]:
k = np.eye(4,6)
k

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [196]:
k = np.eye(4,6)
print(k)
k.ndim

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


2

In [197]:
l = np.random.rand(3,4)
l

array([[0.71957487, 0.25496966, 0.40708644, 0.56997059],
       [0.87188571, 0.37927863, 0.14112542, 0.42315776],
       [0.05752333, 0.7388202 , 0.15973456, 0.06736   ]])

m = np.random.randint((2,10),(4,5))
m

In [198]:
m = np.random.randint((2,4,6,8,3))
m

array([1, 1, 0, 3, 0])

## 27-09-2023

In [199]:
#shape #4 element 2 rows
import numpy
a = numpy.array([[2,3,5,6],[3,5,8,7]])
a.shape

(2, 4)

In [200]:
b = numpy.array([[[[4,5,2,7,8]]]])
b.shape

(1, 1, 1, 5)

In [201]:
c = numpy.array([[3,5,6],[5,7,9],[3,5,8],[3,5,8]])
c.shape

(4, 3)

In [202]:
c = numpy.array([[3,5,6],[5,7,9],[3,5,8]])
c.shape

(3, 3)

In [203]:
d = numpy.array([[3,4,6,7],[7,8,9,8]])
d.shape
d.ndim

2

In [204]:
e = numpy.array([
    [
        [3,4,5],
        [3,5,7],
        [2,8,9],
        [9,6,4],
    ]
])
e.shape

(1, 4, 3)

In [205]:
e.ndim

3

In [206]:
f = numpy.array([3,4,6,5,8])
f[1]
# 0 1 2 3 4
# -4 -3 -2 -1 

4

In [207]:
f[-2]

5

In [208]:
g = numpy.array([
    [7,5,4],
    [4,5,7]
])
g[1,2]


7

In [209]:
g[-1,-2]

5

In [210]:
h = numpy.array([[[5,6,3,7],[2,5,1,8]]])
#h.ndim
h[0]

array([[5, 6, 3, 7],
       [2, 5, 1, 8]])

In [211]:
h[0]

array([[5, 6, 3, 7],
       [2, 5, 1, 8]])

In [212]:
#matrix addition
a = numpy.array([4,3,5,6])
b = numpy.array([3,2,5,6])
a+b

array([ 7,  5, 10, 12])

In [213]:
#matrix subtraction
a = numpy.array([4,3,5,6])
b = numpy.array([3,2,5,6])
a-b

array([1, 1, 0, 0])

In [214]:
#matrix multiplication
a = numpy.array([4,3,5,6])
b = numpy.array([3,2,5,6])
a*b

array([12,  6, 25, 36])

In [215]:
#matrix divison
a = numpy.array([4,3,5,6])
b = numpy.array([3,2,5,6])
a/b

array([1.33333333, 1.5       , 1.        , 1.        ])

In [216]:
#matrix addition
a = numpy.array([[4,3,5,6],[2,3,4,6]])
b = numpy.array([[3,2,5,6],[2,1,3,4]])
a+b

array([[ 7,  5, 10, 12],
       [ 4,  4,  7, 10]])

In [217]:
a-b

array([[1, 1, 0, 0],
       [0, 2, 1, 2]])

In [218]:
a*b

array([[12,  6, 25, 36],
       [ 4,  3, 12, 24]])

In [219]:
z = numpy.array([1,2,4,5])
numpy.reciprocal(z)

array([1, 0, 0, 0])

In [220]:
1/z

array([1.  , 0.5 , 0.25, 0.2 ])

In [221]:
numpy.max(z)

5

In [222]:
numpy.min(z)

1

In [223]:
numpy.sqrt(z)

array([1.        , 1.41421356, 2.        , 2.23606798])

In [224]:
numpy.sin(z)

array([ 0.84147098,  0.90929743, -0.7568025 , -0.95892427])

In [225]:
print(numpy.max(z)) # 5 maximum  3 index position
print(numpy.argmax(z))

5
3


In [226]:
print(numpy.min(z))
print(numpy.argmin(z))

1
0


In [227]:
print(z) #cumsum is the sum of numbers.
print()
print(numpy.cumsum(z))

[1 2 4 5]

[ 1  3  7 12]


In [228]:
import numpy
b = numpy.array([23,13,45,67])
b.nbytes

16

In [229]:
c = numpy.array([[2,3],[4,5]])
c.nbytes

16

In [230]:
b = numpy.array([2,4,6,8])
b.ndim

1

In [231]:
d = b.reshape(2,2)
d

array([[2, 4],
       [6, 8]])

In [126]:
e = numpy.array([1,2,3,4,5,6,7,8,9,1,2,3])
f = e.reshape(4,2)
f

ValueError: cannot reshape array of size 12 into shape (4,2)

In [233]:
g = numpy.array([3,4,5,7,8,9])
g

array([3, 4, 5, 7, 8, 9])

In [234]:
h = g.reshape(2,3)
h

array([[3, 4, 5],
       [7, 8, 9]])

In [235]:
h.ndim

2

In [236]:
g.reshape(1,2,3)

array([[[3, 4, 5],
        [7, 8, 9]]])

In [237]:
h = g.reshape(2,1,3)
h

array([[[3, 4, 5]],

       [[7, 8, 9]]])

In [238]:
h.ndim

3

In [239]:
h[1]

array([[7, 8, 9]])

In [240]:
h[1,0]

array([7, 8, 9])

In [ ]:
#Broadcasting

In [241]:
a = numpy.array([2,3,5,6,7])
b = numpy.array([5])
a+b

array([ 7,  8, 10, 11, 12])

In [242]:
a = numpy.array([[2,3],[4,5]])
a.shape

(2, 2)